using School.Application.DTOs.Student;

namespace School.Web.Models.Students;

public static class StudentFormMapper
{
    public static CreateStudentDto ToCreateDto(StudentFormModel form) => new()
    {
        FinancialYearId         = form.FinancialYearId ?? 0,
        ClassId                 = form.ClassId,
        DivisionId              = form.DivisionId,
        FullName                = form.FullName,
        FirstName               = form.FirstName ?? string.Empty,
        MiddleName              = form.MiddleName ?? string.Empty,
        LastName                = form.LastName ?? string.Empty,
        Gender                  = form.Gender,
        DateOfBirth             = form.DateOfBirth,
        PlaceOfBirth            = form.PlaceOfBirth ?? string.Empty,
        MotherTongue            = form.MotherTongue ?? string.Empty,
        Religion                = form.Religion ?? string.Empty,
        BloodGroup              = form.BloodGroup ?? string.Empty,
        Nationality             = form.Nationality ?? string.Empty,
        NativePlace             = form.NativePlace ?? string.Empty,
        Email                   = form.Email ?? string.Empty,
        FatherName              = form.FatherName ?? string.Empty,
        FatherQualification     = form.FatherQualification ?? string.Empty,
        FatherOccupation        = form.FatherOccupation ?? string.Empty,
        FatherIncome            = form.FatherIncome,
        FatherMobile            = form.FatherMobile ?? string.Empty,
        MotherName              = form.MotherName ?? string.Empty,
        MotherQualification     = form.MotherQualification ?? string.Empty,
        MotherMobile            = form.MotherMobile ?? string.Empty,
        GuardianName            = form.GuardianName ?? string.Empty,
        GuardianRelation        = form.GuardianRelation ?? string.Empty,
        GuardianMobile          = form.GuardianMobile ?? string.Empty,
        FlatNo                  = form.FlatNo ?? string.Empty,
        Building                = form.Building ?? string.Empty,
        Area                    = form.Area ?? string.Empty,
        City                    = form.City ?? string.Empty,
        Landmark                = form.Landmark ?? string.Empty,
        District                = form.District ?? string.Empty,
        State                   = form.State ?? string.Empty,
        PinCode                 = form.PinCode ?? string.Empty,
        FatherPhone             = form.FatherPhone ?? string.Empty,
        MotherPhone             = form.MotherPhone ?? string.Empty,
        GuardianPhone           = form.GuardianPhone ?? string.Empty,
        WhatsAppNo              = form.WhatsAppNo ?? string.Empty,
        ContactEmail            = form.ContactEmail ?? string.Empty,
        LastSchoolAttended      = form.LastSchoolAttended ?? string.Empty,
        PreviousClass           = form.PreviousClass ?? string.Empty,
        Medium                  = form.Medium ?? string.Empty,
        AdmissionDate           = form.AdmissionDate,
        ReceiptNo               = form.ReceiptNo ?? string.Empty,
        FormNo                  = form.FormNo ?? string.Empty,
        AcademicYearId          = form.AcademicYearId,
        AdmissionConfirmedClass = form.AdmissionConfirmedClass ?? string.Empty,
        ClerkName               = form.ClerkName ?? string.Empty
    };

    public static EditStudentDto ToEditDto(StudentFormModel form) => new()
    {
        Id                      = form.Id,
        ClassId                 = form.ClassId!.Value,
        DivisionId              = form.DivisionId!.Value,
        FullName                = form.FullName,
        FirstName               = form.FirstName ?? string.Empty,
        MiddleName              = form.MiddleName ?? string.Empty,
        LastName                = form.LastName ?? string.Empty,
        Gender                  = form.Gender,
        DateOfBirth             = form.DateOfBirth,
        PlaceOfBirth            = form.PlaceOfBirth ?? string.Empty,
        MotherTongue            = form.MotherTongue ?? string.Empty,
        Religion                = form.Religion ?? string.Empty,
        BloodGroup              = form.BloodGroup ?? string.Empty,
        Nationality             = form.Nationality ?? string.Empty,
        NativePlace             = form.NativePlace ?? string.Empty,
        Email                   = form.Email ?? string.Empty,
        IsActive                = form.IsActive,
        FatherName              = form.FatherName ?? string.Empty,
        FatherQualification     = form.FatherQualification ?? string.Empty,
        FatherOccupation        = form.FatherOccupation ?? string.Empty,
        FatherIncome            = form.FatherIncome,
        FatherMobile            = form.FatherMobile ?? string.Empty,
        MotherName              = form.MotherName ?? string.Empty,
        MotherQualification     = form.MotherQualification ?? string.Empty,
        MotherMobile            = form.MotherMobile ?? string.Empty,
        GuardianName            = form.GuardianName ?? string.Empty,
        GuardianRelation        = form.GuardianRelation ?? string.Empty,
        GuardianMobile          = form.GuardianMobile ?? string.Empty,
        FlatNo                  = form.FlatNo ?? string.Empty,
        Building                = form.Building ?? string.Empty,
        Area                    = form.Area ?? string.Empty,
        City                    = form.City ?? string.Empty,
        Landmark                = form.Landmark ?? string.Empty,
        District                = form.District ?? string.Empty,
        State                   = form.State ?? string.Empty,
        PinCode                 = form.PinCode ?? string.Empty,
        FatherPhone             = form.FatherPhone ?? string.Empty,
        MotherPhone             = form.MotherPhone ?? string.Empty,
        GuardianPhone           = form.GuardianPhone ?? string.Empty,
        WhatsAppNo              = form.WhatsAppNo ?? string.Empty,
        ContactEmail            = form.ContactEmail ?? string.Empty,
        LastSchoolAttended      = form.LastSchoolAttended ?? string.Empty,
        PreviousClass           = form.PreviousClass ?? string.Empty,
        Medium                  = form.Medium ?? string.Empty,
        AdmissionDate           = form.AdmissionDate,
        ReceiptNo               = form.ReceiptNo ?? string.Empty,
        FormNo                  = form.FormNo ?? string.Empty,
        AcademicYearId          = form.AcademicYearId,
        AdmissionConfirmedClass = form.AdmissionConfirmedClass ?? string.Empty,
        ClerkName               = form.ClerkName ?? string.Empty
    };
}
